package com.xahertz.sentinel;

import javax.swing.JOptionPane;

/**
 *
 * @author XaHertz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        Version = "0.4.0";
        Vault_Table_Name = "Root";
        com.xahertz.internal.SQLite.initVaultList();
        initComponents();
        Container_Deck = (java.awt.CardLayout)Container.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Passwords_Table_PopupMenu = new javax.swing.JPopupMenu();
        Table_PopupMenu_New_Entry = new javax.swing.JMenuItem();
        Table_PopupMenu_Edit_Entry = new javax.swing.JMenuItem();
        Table_PopupMenu_Delete_Entry = new javax.swing.JMenuItem();
        Table_PopupMenu_Separator = new javax.swing.JPopupMenu.Separator();
        Table_PopupMenu_Copy_Username = new javax.swing.JMenuItem();
        Table_PopupMenu_Copy_Password = new javax.swing.JMenuItem();
        Table_PopupMenu_Copy_URL = new javax.swing.JMenuItem();
        FolderTree_PopupMenu = new javax.swing.JPopupMenu();
        Tree_PopupMenu_New_Group = new javax.swing.JMenuItem();
        Tree_PopupMenu_Edit_Group = new javax.swing.JMenuItem();
        Tree_PopupMenu_Delete_Group = new javax.swing.JMenuItem();
        Main_ToolBar = new javax.swing.JToolBar();
        Open_Vault_Button = new javax.swing.JButton();
        Close_Vault_Button = new javax.swing.JButton();
        ToolBar_Separator_One = new javax.swing.JToolBar.Separator();
        New_Entry_Button = new javax.swing.JButton();
        Edit_Entry_Button = new javax.swing.JButton();
        Delete_Entry_Button = new javax.swing.JButton();
        ToolBar_Separator_Two = new javax.swing.JToolBar.Separator();
        Copy_Username_Button = new javax.swing.JButton();
        Copy_Password_Button = new javax.swing.JButton();
        Copy_URL_Button = new javax.swing.JButton();
        Password_Generator_Button = new javax.swing.JButton();
        ToolBar_Separator_Three = new javax.swing.JToolBar.Separator();
        About_Button = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        StartPage = new javax.swing.JPanel();
        Welcome_Label = new javax.swing.JLabel();
        Vault_Actions_Panel = new javax.swing.JPanel();
        StartPage_Create_Vault_Button = new javax.swing.JButton();
        StartPage_Open_Vault_Button = new javax.swing.JButton();
        Recent_Vaults_Label = new javax.swing.JLabel();
        Recent_Vaults_ScrollPane = new javax.swing.JScrollPane();
        Recent_Vaults_List = new javax.swing.JList<>();
        NewVaultPage = new javax.swing.JPanel();
        NewVault_Label = new javax.swing.JLabel();
        NewVault_Container = new javax.swing.JPanel();
        Vault_Name_Label = new javax.swing.JLabel();
        Vault_Name_Field = new javax.swing.JTextField();
        Vault_Password_Label = new javax.swing.JLabel();
        Vault_Password_Field = new javax.swing.JPasswordField();
        Confirm_Password_Label = new javax.swing.JLabel();
        Confirm_Password_Field = new javax.swing.JPasswordField();
        Vault_Location_Label = new javax.swing.JLabel();
        Vault_Location_Field = new javax.swing.JTextField();
        Browse_Button = new javax.swing.JButton();
        NewVault_Cancel_Button = new javax.swing.JButton();
        NewVault_Finish_Button = new javax.swing.JButton();
        VaultPage = new javax.swing.JPanel();
        FolderTree_ScrollPane = new javax.swing.JScrollPane();
        FolderTree = new javax.swing.JTree();
        Passwords_Table_ScrollPane = new javax.swing.JScrollPane();
        Passwords_Table = new javax.swing.JTable();
        Details_Panel = new javax.swing.JPanel();
        EntryPage = new javax.swing.JPanel();
        EntryPage_Label = new javax.swing.JLabel();
        EntryPage_Container = new javax.swing.JPanel();
        Title_Label = new javax.swing.JLabel();
        Title_TextField = new javax.swing.JTextField();
        Username_Label = new javax.swing.JLabel();
        Username_TextField = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        Generate_Password_Button = new javax.swing.JButton();
        URL_Label = new javax.swing.JLabel();
        URL_TextField = new javax.swing.JTextField();
        Notes_Label = new javax.swing.JLabel();
        Notes_ScrollPane = new javax.swing.JScrollPane();
        Notes_TextArea = new javax.swing.JTextArea();
        EntryPage_Cancel_Button = new javax.swing.JButton();
        EntryPage_Finish_Button = new javax.swing.JButton();
        Menu_Bar = new javax.swing.JMenuBar();
        Vault_Menu = new javax.swing.JMenu();
        New_Vault_MenuItem = new javax.swing.JMenuItem();
        Open_Vault_MenuItem = new javax.swing.JMenuItem();
        Close_Vault_MenuItem = new javax.swing.JMenuItem();
        Vault_Menu_Separator_One = new javax.swing.JPopupMenu.Separator();
        Exit_MenuItem = new javax.swing.JMenuItem();
        Edit_Menu = new javax.swing.JMenu();
        New_Entry_MenuItem = new javax.swing.JMenuItem();
        Edit_Entry_MenuItem = new javax.swing.JMenuItem();
        Delete_Entry_MenuItem = new javax.swing.JMenuItem();
        Edit_Menu_Separator_One = new javax.swing.JPopupMenu.Separator();
        New_Group_MenuItem = new javax.swing.JMenuItem();
        Edit_Group_MenuItem = new javax.swing.JMenuItem();
        Delete_Group_MenuItem = new javax.swing.JMenuItem();
        Edit_Menu_Separator_Two = new javax.swing.JPopupMenu.Separator();
        Copy_Username_MenuItem = new javax.swing.JMenuItem();
        Copy_Password_MenuItem = new javax.swing.JMenuItem();
        Copy_URL_MenuItem = new javax.swing.JMenuItem();
        Tools_Menu = new javax.swing.JMenu();
        Password_Generator_MenuItem = new javax.swing.JMenuItem();
        AutoType_Menu = new javax.swing.JMenu();
        AutoType_All_MenuItem = new javax.swing.JMenuItem();
        AutoType_Usename_MenuItem = new javax.swing.JMenuItem();
        AutoType_Password_MenuItem = new javax.swing.JMenuItem();
        Help_Menu = new javax.swing.JMenu();
        About_MenuItem = new javax.swing.JMenuItem();

        Table_PopupMenu_New_Entry.setText("New Entry");
        Passwords_Table_PopupMenu.add(Table_PopupMenu_New_Entry);

        Table_PopupMenu_Edit_Entry.setText("Edit Entry");
        Passwords_Table_PopupMenu.add(Table_PopupMenu_Edit_Entry);

        Table_PopupMenu_Delete_Entry.setText("Delete Entry");
        Passwords_Table_PopupMenu.add(Table_PopupMenu_Delete_Entry);
        Passwords_Table_PopupMenu.add(Table_PopupMenu_Separator);

        Table_PopupMenu_Copy_Username.setText("Copy Username");
        Passwords_Table_PopupMenu.add(Table_PopupMenu_Copy_Username);

        Table_PopupMenu_Copy_Password.setText("Copy Password");
        Passwords_Table_PopupMenu.add(Table_PopupMenu_Copy_Password);

        Table_PopupMenu_Copy_URL.setText("Copy URL");
        Passwords_Table_PopupMenu.add(Table_PopupMenu_Copy_URL);

        Tree_PopupMenu_New_Group.setText("New Group");
        FolderTree_PopupMenu.add(Tree_PopupMenu_New_Group);

        Tree_PopupMenu_Edit_Group.setText("Edit Group");
        FolderTree_PopupMenu.add(Tree_PopupMenu_Edit_Group);

        Tree_PopupMenu_Delete_Group.setText("Delete Group");
        FolderTree_PopupMenu.add(Tree_PopupMenu_Delete_Group);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sentinel");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/app-icon.png")).getImage());
        setLocationByPlatform(true);

        Main_ToolBar.setRollover(true);

        Open_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        Open_Vault_Button.setToolTipText("Open Existing Vault");
        Open_Vault_Button.setFocusable(false);
        Open_Vault_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Open_Vault_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Open_Vault_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Vault_ButtonActionPerformed(evt);
            }
        });
        Main_ToolBar.add(Open_Vault_Button);

        Close_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unlock.png"))); // NOI18N
        Close_Vault_Button.setToolTipText("Close Vault");
        Close_Vault_Button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock-disabled.png"))); // NOI18N
        Close_Vault_Button.setEnabled(false);
        Close_Vault_Button.setFocusable(false);
        Close_Vault_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close_Vault_Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N
        Close_Vault_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Close_Vault_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_Vault_ButtonActionPerformed(evt);
            }
        });
        Main_ToolBar.add(Close_Vault_Button);
        Main_ToolBar.add(ToolBar_Separator_One);

        New_Entry_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        New_Entry_Button.setToolTipText("Add a New Entry");
        New_Entry_Button.setEnabled(false);
        New_Entry_Button.setFocusable(false);
        New_Entry_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New_Entry_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        New_Entry_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Entry_ButtonActionPerformed(evt);
            }
        });
        Main_ToolBar.add(New_Entry_Button);

        Edit_Entry_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        Edit_Entry_Button.setToolTipText("Edit an Entry");
        Edit_Entry_Button.setEnabled(false);
        Edit_Entry_Button.setFocusable(false);
        Edit_Entry_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Edit_Entry_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Edit_Entry_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_Entry_ButtonActionPerformed(evt);
            }
        });
        Main_ToolBar.add(Edit_Entry_Button);

        Delete_Entry_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        Delete_Entry_Button.setToolTipText("Delete an Entry");
        Delete_Entry_Button.setEnabled(false);
        Delete_Entry_Button.setFocusable(false);
        Delete_Entry_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Delete_Entry_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Delete_Entry_Button);
        Main_ToolBar.add(ToolBar_Separator_Two);

        Copy_Username_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        Copy_Username_Button.setToolTipText("Copy Username");
        Copy_Username_Button.setEnabled(false);
        Copy_Username_Button.setFocusable(false);
        Copy_Username_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Copy_Username_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Copy_Username_Button);

        Copy_Password_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
        Copy_Password_Button.setToolTipText("Copy Password");
        Copy_Password_Button.setEnabled(false);
        Copy_Password_Button.setFocusable(false);
        Copy_Password_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Copy_Password_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Copy_Password_Button);

        Copy_URL_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/globe.png"))); // NOI18N
        Copy_URL_Button.setToolTipText("Copy URL");
        Copy_URL_Button.setEnabled(false);
        Copy_URL_Button.setFocusable(false);
        Copy_URL_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Copy_URL_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Copy_URL_Button);

        Password_Generator_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/electronics.png"))); // NOI18N
        Password_Generator_Button.setToolTipText("Password Generator");
        Password_Generator_Button.setFocusable(false);
        Password_Generator_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Password_Generator_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Password_Generator_Button);
        Main_ToolBar.add(ToolBar_Separator_Three);

        About_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        About_Button.setFocusable(false);
        About_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        About_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        About_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_ButtonActionPerformed(evt);
            }
        });
        Main_ToolBar.add(About_Button);

        Container.setLayout(new java.awt.CardLayout());

        Welcome_Label.setFont(Welcome_Label.getFont().deriveFont(Welcome_Label.getFont().getSize()+24f));
        Welcome_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome_Label.setText("Welcome to Sentinel");

        Vault_Actions_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StartPage_Create_Vault_Button.setFont(StartPage_Create_Vault_Button.getFont().deriveFont(StartPage_Create_Vault_Button.getFont().getStyle() | java.awt.Font.BOLD, StartPage_Create_Vault_Button.getFont().getSize()+2));
        StartPage_Create_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vault.png"))); // NOI18N
        StartPage_Create_Vault_Button.setText("Create New Vault");
        StartPage_Create_Vault_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPage_Create_Vault_ButtonActionPerformed(evt);
            }
        });

        StartPage_Open_Vault_Button.setFont(StartPage_Open_Vault_Button.getFont().deriveFont(StartPage_Open_Vault_Button.getFont().getStyle() | java.awt.Font.BOLD, StartPage_Open_Vault_Button.getFont().getSize()+2));
        StartPage_Open_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        StartPage_Open_Vault_Button.setText("Open Existing Vault");
        StartPage_Open_Vault_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPage_Open_Vault_ButtonActionPerformed(evt);
            }
        });

        Recent_Vaults_Label.setFont(Recent_Vaults_Label.getFont().deriveFont(Recent_Vaults_Label.getFont().getStyle() | java.awt.Font.BOLD));
        Recent_Vaults_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Recent_Vaults_Label.setText("Recent Vaults");

        Recent_Vaults_List.setModel(com.xahertz.internal.SQLite.getVaultList());
        Recent_Vaults_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Recent_Vaults_ListMouseClicked(evt);
            }
        });
        Recent_Vaults_ScrollPane.setViewportView(Recent_Vaults_List);

        javax.swing.GroupLayout Vault_Actions_PanelLayout = new javax.swing.GroupLayout(Vault_Actions_Panel);
        Vault_Actions_Panel.setLayout(Vault_Actions_PanelLayout);
        Vault_Actions_PanelLayout.setHorizontalGroup(
            Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vault_Actions_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Recent_Vaults_ScrollPane)
                    .addGroup(Vault_Actions_PanelLayout.createSequentialGroup()
                        .addComponent(StartPage_Create_Vault_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartPage_Open_Vault_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Recent_Vaults_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Vault_Actions_PanelLayout.setVerticalGroup(
            Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vault_Actions_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartPage_Create_Vault_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartPage_Open_Vault_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Recent_Vaults_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recent_Vaults_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout StartPageLayout = new javax.swing.GroupLayout(StartPage);
        StartPage.setLayout(StartPageLayout);
        StartPageLayout.setHorizontalGroup(
            StartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPageLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(StartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vault_Actions_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Welcome_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        StartPageLayout.setVerticalGroup(
            StartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPageLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(Welcome_Label)
                .addGap(18, 18, 18)
                .addComponent(Vault_Actions_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        Container.add(StartPage, "start");

        NewVault_Label.setFont(NewVault_Label.getFont().deriveFont(NewVault_Label.getFont().getSize()+12f));
        NewVault_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NewVault_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vault.png"))); // NOI18N
        NewVault_Label.setText(" Create New Vault");

        NewVault_Container.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Vault_Name_Label.setFont(Vault_Name_Label.getFont().deriveFont(Vault_Name_Label.getFont().getSize()+2f));
        Vault_Name_Label.setText("Vault Name");

        Vault_Password_Label.setFont(Vault_Password_Label.getFont().deriveFont(Vault_Password_Label.getFont().getSize()+2f));
        Vault_Password_Label.setText("Vault Password");

        Confirm_Password_Label.setFont(Confirm_Password_Label.getFont().deriveFont(Confirm_Password_Label.getFont().getSize()+2f));
        Confirm_Password_Label.setText("Confirm Password");

        Vault_Location_Label.setFont(Vault_Location_Label.getFont().deriveFont(Vault_Location_Label.getFont().getSize()+2f));
        Vault_Location_Label.setText("Vault Location");

        Browse_Button.setText("Browse");
        Browse_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewVault_ContainerLayout = new javax.swing.GroupLayout(NewVault_Container);
        NewVault_Container.setLayout(NewVault_ContainerLayout);
        NewVault_ContainerLayout.setHorizontalGroup(
            NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewVault_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Vault_Location_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Confirm_Password_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(Vault_Password_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vault_Name_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vault_Password_Field)
                    .addComponent(Confirm_Password_Field)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewVault_ContainerLayout.createSequentialGroup()
                        .addComponent(Vault_Location_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Browse_Button))
                    .addComponent(Vault_Name_Field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewVault_ContainerLayout.setVerticalGroup(
            NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewVault_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vault_Name_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Vault_Name_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewVault_ContainerLayout.createSequentialGroup()
                        .addComponent(Vault_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(Vault_Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Confirm_Password_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Confirm_Password_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewVault_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Vault_Location_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(Vault_Location_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Browse_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewVault_Cancel_Button.setFont(NewVault_Cancel_Button.getFont().deriveFont(NewVault_Cancel_Button.getFont().getSize()+2f));
        NewVault_Cancel_Button.setText("Cancel");
        NewVault_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewVault_Cancel_ButtonActionPerformed(evt);
            }
        });

        NewVault_Finish_Button.setFont(NewVault_Finish_Button.getFont().deriveFont(NewVault_Finish_Button.getFont().getSize()+2f));
        NewVault_Finish_Button.setText("Finish");
        NewVault_Finish_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewVault_Finish_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewVaultPageLayout = new javax.swing.GroupLayout(NewVaultPage);
        NewVaultPage.setLayout(NewVaultPageLayout);
        NewVaultPageLayout.setHorizontalGroup(
            NewVaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewVaultPageLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(NewVaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(NewVaultPageLayout.createSequentialGroup()
                        .addComponent(NewVault_Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(560, 560, 560)
                        .addComponent(NewVault_Finish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NewVault_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewVault_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        NewVaultPageLayout.setVerticalGroup(
            NewVaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewVaultPageLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(NewVault_Label)
                .addGap(18, 18, 18)
                .addComponent(NewVault_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NewVaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewVault_Finish_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(NewVault_Cancel_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        Container.add(NewVaultPage, "new");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Work");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Entertainment");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Social");
        treeNode1.add(treeNode2);
        FolderTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        FolderTree.setComponentPopupMenu(FolderTree_PopupMenu);
        FolderTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FolderTreeMousePressed(evt);
            }
        });
        FolderTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                FolderTreeValueChanged(evt);
            }
        });
        FolderTree_ScrollPane.setViewportView(FolderTree);

        Passwords_Table.setAutoCreateRowSorter(true);
        Passwords_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Username", "URL", "Notes"
            }
        ));
        Passwords_Table.setComponentPopupMenu(Passwords_Table_PopupMenu);
        Passwords_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Passwords_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Passwords_TableMousePressed(evt);
            }
        });
        Passwords_Table_ScrollPane.setViewportView(Passwords_Table);

        Details_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout Details_PanelLayout = new javax.swing.GroupLayout(Details_Panel);
        Details_Panel.setLayout(Details_PanelLayout);
        Details_PanelLayout.setHorizontalGroup(
            Details_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Details_PanelLayout.setVerticalGroup(
            Details_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout VaultPageLayout = new javax.swing.GroupLayout(VaultPage);
        VaultPage.setLayout(VaultPageLayout);
        VaultPageLayout.setHorizontalGroup(
            VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VaultPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FolderTree_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwords_Table_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addComponent(Details_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        VaultPageLayout.setVerticalGroup(
            VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VaultPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FolderTree_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(VaultPageLayout.createSequentialGroup()
                        .addComponent(Passwords_Table_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Details_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Container.add(VaultPage, "vault");

        EntryPage_Label.setFont(EntryPage_Label.getFont().deriveFont(EntryPage_Label.getFont().getSize()+12f));
        EntryPage_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EntryPage_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
        EntryPage_Label.setText("Entry Page");

        EntryPage_Container.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Title_Label.setFont(Title_Label.getFont().deriveFont(Title_Label.getFont().getSize()+2f));
        Title_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Title_Label.setText("Title");

        Username_Label.setFont(Username_Label.getFont().deriveFont(Username_Label.getFont().getSize()+2f));
        Username_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Username_Label.setText("Username");

        Password_Label.setFont(Password_Label.getFont().deriveFont(Password_Label.getFont().getSize()+2f));
        Password_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Password_Label.setText("Password");

        Generate_Password_Button.setText("Generate Password");

        URL_Label.setFont(URL_Label.getFont().deriveFont(URL_Label.getFont().getSize()+2f));
        URL_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        URL_Label.setText("URL");

        Notes_Label.setFont(Notes_Label.getFont().deriveFont(Notes_Label.getFont().getSize()+2f));
        Notes_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Notes_Label.setText("Notes");

        Notes_TextArea.setColumns(20);
        Notes_TextArea.setRows(5);
        Notes_ScrollPane.setViewportView(Notes_TextArea);

        javax.swing.GroupLayout EntryPage_ContainerLayout = new javax.swing.GroupLayout(EntryPage_Container);
        EntryPage_Container.setLayout(EntryPage_ContainerLayout);
        EntryPage_ContainerLayout.setHorizontalGroup(
            EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryPage_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Notes_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(URL_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Username_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntryPage_ContainerLayout.createSequentialGroup()
                        .addComponent(Password_Field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Generate_Password_Button))
                    .addComponent(Title_TextField)
                    .addComponent(URL_TextField)
                    .addComponent(Username_TextField)
                    .addComponent(Notes_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
                .addContainerGap())
        );
        EntryPage_ContainerLayout.setVerticalGroup(
            EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryPage_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Title_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Username_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Username_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Generate_Password_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Password_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password_Field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(URL_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(URL_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EntryPage_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Notes_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(Notes_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        EntryPage_Cancel_Button.setFont(EntryPage_Cancel_Button.getFont().deriveFont(EntryPage_Cancel_Button.getFont().getSize()+2f));
        EntryPage_Cancel_Button.setText("Cancel");
        EntryPage_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPage_Cancel_ButtonActionPerformed(evt);
            }
        });

        EntryPage_Finish_Button.setFont(EntryPage_Finish_Button.getFont().deriveFont(EntryPage_Finish_Button.getFont().getSize()+2f));
        EntryPage_Finish_Button.setText("Finish");
        EntryPage_Finish_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPage_Finish_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EntryPageLayout = new javax.swing.GroupLayout(EntryPage);
        EntryPage.setLayout(EntryPageLayout);
        EntryPageLayout.setHorizontalGroup(
            EntryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryPageLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(EntryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EntryPageLayout.createSequentialGroup()
                        .addComponent(EntryPage_Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntryPage_Finish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EntryPage_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EntryPage_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        EntryPageLayout.setVerticalGroup(
            EntryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryPageLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(EntryPage_Label)
                .addGap(18, 18, 18)
                .addComponent(EntryPage_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(EntryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryPage_Cancel_Button)
                    .addComponent(EntryPage_Finish_Button))
                .addGap(50, 50, 50))
        );

        Container.add(EntryPage, "entry");

        Vault_Menu.setText("Vault");

        New_Vault_MenuItem.setText("New Vault");
        New_Vault_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Vault_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(New_Vault_MenuItem);

        Open_Vault_MenuItem.setText("Open Vault");
        Open_Vault_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Vault_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(Open_Vault_MenuItem);

        Close_Vault_MenuItem.setText("Close Vault");
        Close_Vault_MenuItem.setEnabled(false);
        Close_Vault_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_Vault_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(Close_Vault_MenuItem);
        Vault_Menu.add(Vault_Menu_Separator_One);

        Exit_MenuItem.setText("Exit");
        Exit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(Exit_MenuItem);

        Menu_Bar.add(Vault_Menu);

        Edit_Menu.setText("Edit");

        New_Entry_MenuItem.setText("New Entry");
        New_Entry_MenuItem.setEnabled(false);
        Edit_Menu.add(New_Entry_MenuItem);

        Edit_Entry_MenuItem.setText("Edit Entry");
        Edit_Entry_MenuItem.setEnabled(false);
        Edit_Menu.add(Edit_Entry_MenuItem);

        Delete_Entry_MenuItem.setText("Delete Entry");
        Delete_Entry_MenuItem.setEnabled(false);
        Edit_Menu.add(Delete_Entry_MenuItem);
        Edit_Menu.add(Edit_Menu_Separator_One);

        New_Group_MenuItem.setText("New Group");
        New_Group_MenuItem.setEnabled(false);
        Edit_Menu.add(New_Group_MenuItem);

        Edit_Group_MenuItem.setText("Edit Group");
        Edit_Group_MenuItem.setEnabled(false);
        Edit_Menu.add(Edit_Group_MenuItem);

        Delete_Group_MenuItem.setText("Delete Group");
        Delete_Group_MenuItem.setEnabled(false);
        Edit_Menu.add(Delete_Group_MenuItem);
        Edit_Menu.add(Edit_Menu_Separator_Two);

        Copy_Username_MenuItem.setText("Copy Username");
        Copy_Username_MenuItem.setEnabled(false);
        Edit_Menu.add(Copy_Username_MenuItem);

        Copy_Password_MenuItem.setText("Copy Password");
        Copy_Password_MenuItem.setEnabled(false);
        Edit_Menu.add(Copy_Password_MenuItem);

        Copy_URL_MenuItem.setText("Copy URL");
        Copy_URL_MenuItem.setEnabled(false);
        Edit_Menu.add(Copy_URL_MenuItem);

        Menu_Bar.add(Edit_Menu);

        Tools_Menu.setText("Tools");

        Password_Generator_MenuItem.setText("Password Generator");
        Tools_Menu.add(Password_Generator_MenuItem);

        AutoType_Menu.setText("Perform Auto-Type");
        AutoType_Menu.setEnabled(false);

        AutoType_All_MenuItem.setText("Username and Password");
        AutoType_Menu.add(AutoType_All_MenuItem);

        AutoType_Usename_MenuItem.setText("Username");
        AutoType_Menu.add(AutoType_Usename_MenuItem);

        AutoType_Password_MenuItem.setText("Password");
        AutoType_Menu.add(AutoType_Password_MenuItem);

        Tools_Menu.add(AutoType_Menu);

        Menu_Bar.add(Tools_Menu);

        Help_Menu.setText("Help");

        About_MenuItem.setText("About");
        About_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_MenuItemActionPerformed(evt);
            }
        });
        Help_Menu.add(About_MenuItem);

        Menu_Bar.add(Help_Menu);

        setJMenuBar(Menu_Bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Main_ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Main_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_MenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_MenuItemActionPerformed

    private void StartPage_Create_Vault_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPage_Create_Vault_ButtonActionPerformed
        Container_Deck.show(Container, "new");
    }//GEN-LAST:event_StartPage_Create_Vault_ButtonActionPerformed

    private void Close_Vault_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_Vault_ButtonActionPerformed
        com.xahertz.internal.SQLite.closeVault();
        CloseVaultPage();
    }//GEN-LAST:event_Close_Vault_ButtonActionPerformed

    private void Close_Vault_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_Vault_MenuItemActionPerformed
        com.xahertz.internal.SQLite.closeVault();
        CloseVaultPage();
    }//GEN-LAST:event_Close_Vault_MenuItemActionPerformed

    private void Open_Vault_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Vault_MenuItemActionPerformed
        if (com.xahertz.internal.Functions.openVault())
            OpenVaultPage();
    }//GEN-LAST:event_Open_Vault_MenuItemActionPerformed

    private void Passwords_TableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Passwords_TableMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            int row = Passwords_Table.rowAtPoint(evt.getPoint());
            int column = Passwords_Table.columnAtPoint(evt.getPoint());
            if (!Passwords_Table.isRowSelected(row))
                Passwords_Table.changeSelection(row, column, false, false);
        }
    }//GEN-LAST:event_Passwords_TableMousePressed

    private void NewVault_Finish_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewVault_Finish_ButtonActionPerformed
        String vltName = Vault_Name_Field.getText();
        String vltPass = new String(Vault_Password_Field.getPassword());
        String cnfPass = new String(Confirm_Password_Field.getPassword());
        String vltPath = Vault_Location_Field.getText();
        if (vltName.equals("") || vltPass.equals("") || cnfPass.equals("") || vltPath.equals(""))
            JOptionPane.showMessageDialog(null, "All Fields are Required to be Filled. Please Try Again!", "Empty Feilds", JOptionPane.ERROR_MESSAGE);
        else if (vltPass.length() < 8)
            JOptionPane.showMessageDialog(null, "Your Password Must Contain at Least 8 Characters. Please Try Again!", "Password Too Short", JOptionPane.ERROR_MESSAGE);
        else if (!vltPass.equals(cnfPass))
            JOptionPane.showMessageDialog(null, "The Passwords in Password Fields do not Match. Please Try Again!", "Password Mismatch", JOptionPane.ERROR_MESSAGE);
        else {
            com.xahertz.internal.SQLite.createNewVault(vltName, vltPass, vltPath);
            com.xahertz.internal.SQLite.setVaultList(vltPath);
            Vault_Name_Field.setText("");
            Vault_Password_Field.setText("");
            Confirm_Password_Field.setText("");
            Vault_Location_Field.setText("");
            OpenVaultPage();
        }
    }//GEN-LAST:event_NewVault_Finish_ButtonActionPerformed

    private void NewVault_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewVault_Cancel_ButtonActionPerformed
        Container_Deck.show(Container, "start");
    }//GEN-LAST:event_NewVault_Cancel_ButtonActionPerformed

    private void StartPage_Open_Vault_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPage_Open_Vault_ButtonActionPerformed
        if (com.xahertz.internal.Functions.openVault())
            OpenVaultPage();
    }//GEN-LAST:event_StartPage_Open_Vault_ButtonActionPerformed

    private void Open_Vault_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Vault_ButtonActionPerformed
        if (com.xahertz.internal.Functions.openVault())
            OpenVaultPage();
    }//GEN-LAST:event_Open_Vault_ButtonActionPerformed

    private void New_Vault_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Vault_MenuItemActionPerformed
        Container_Deck.show(Container, "new");
    }//GEN-LAST:event_New_Vault_MenuItemActionPerformed

    private void Browse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse_ButtonActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Save Vault as");
        fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fileChooser.setSelectedFile(new java.io.File("Passwords.vault"));
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Sentinel Vault File", "vault"));
        if (fileChooser.showSaveDialog(null) == javax.swing.JFileChooser.APPROVE_OPTION) {
            if (fileChooser.getSelectedFile().exists()) {
                int response = JOptionPane.showConfirmDialog(null, "The file already exists. Do you want to overwrite the file?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    Vault_Location_Field.setText(fileChooser.getSelectedFile().getAbsolutePath());
                }
            } else
                Vault_Location_Field.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_Browse_ButtonActionPerformed

    private void About_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_ButtonActionPerformed
        JOptionPane.showMessageDialog(null, "<html><h1>Sentinel Password Manager</h1></html>\nVersion " + Version + "\nCopyright \u00A9 2024 XaHertz", "About", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_About_ButtonActionPerformed

    private void About_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_MenuItemActionPerformed
        JOptionPane.showMessageDialog(null, "<html><h1>Sentinel Password Manager</h1></html>\nVersion " + Version + "\nCopyright \u00A9 2024 XaHertz", "About", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_About_MenuItemActionPerformed

    private void Recent_Vaults_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Recent_Vaults_ListMouseClicked
        javax.swing.JList list = (javax.swing.JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            String vltPass = JOptionPane.showInputDialog(null, "Vault File: " + list.getSelectedValue(), "Enter Password", JOptionPane.PLAIN_MESSAGE);
            if (vltPass != null) {
                if (!vltPass.equals("")) {
                    com.xahertz.internal.SQLite.openVault(list.getSelectedValue().toString(), vltPass);
                    OpenVaultPage();
                }
            }
        }
    }//GEN-LAST:event_Recent_Vaults_ListMouseClicked

    private void New_Entry_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Entry_ButtonActionPerformed
        EntryPage_Label.setText(Vault_Table_Name + " \u2022 New Entry");
        Container_Deck.show(Container, "entry");
        DisableVaultDataManipulationFunctions();
    }//GEN-LAST:event_New_Entry_ButtonActionPerformed

    private void EntryPage_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPage_Cancel_ButtonActionPerformed
        Container_Deck.show(Container, "vault");
        EnableVaultDataManipulationFunctions();
        Title_TextField.setText("");
        Username_TextField.setText("");
        Password_Field.setText("");
        URL_TextField.setText("");
        Notes_TextArea.setText("");
    }//GEN-LAST:event_EntryPage_Cancel_ButtonActionPerformed

    private void EntryPage_Finish_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPage_Finish_ButtonActionPerformed
        String UID = "SVLT-" + new java.text.SimpleDateFormat("yyMMdd-HHmmss").format(new java.util.Date())+ "-" + com.xahertz.internal.Functions.randomID(8);
        String Title = Title_TextField.getText();
        String Username = Username_TextField.getText();
        String Password = new String(Password_Field.getPassword());
        String URL = URL_TextField.getText();
        String Notes = Notes_TextArea.getText();
        com.xahertz.internal.SQLite.newTableEntry(Vault_Table_Name, UID, Title, Username, Password, URL, Notes);
        Passwords_Table.setModel(com.xahertz.internal.Functions.vltTableModel(Vault_Table_Name));
        Container_Deck.show(Container, "vault");
        EnableVaultDataManipulationFunctions();
        Title_TextField.setText("");
        Username_TextField.setText("");
        Password_Field.setText("");
        URL_TextField.setText("");
        Notes_TextArea.setText("");
    }//GEN-LAST:event_EntryPage_Finish_ButtonActionPerformed

    private void Edit_Entry_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Entry_ButtonActionPerformed
        EntryPage_Label.setText(Vault_Table_Name + " \u2022 Edit Entry");
        Container_Deck.show(Container, "entry");
        DisableVaultDataManipulationFunctions();
    }//GEN-LAST:event_Edit_Entry_ButtonActionPerformed

    private void FolderTreeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FolderTreeMousePressed
        javax.swing.tree.TreePath selPath = FolderTree.getClosestPathForLocation(evt.getX(), evt.getY());
        FolderTree.setSelectionPath(selPath);
    }//GEN-LAST:event_FolderTreeMousePressed

    private void FolderTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_FolderTreeValueChanged
        String vltTableName = evt.getNewLeadSelectionPath().getLastPathComponent().toString();
        Passwords_Table.setModel(com.xahertz.internal.Functions.vltTableModel(vltTableName));
        Vault_Table_Name = vltTableName;
    }//GEN-LAST:event_FolderTreeValueChanged

    private void OpenVaultPage() {
        Recent_Vaults_List.setModel(com.xahertz.internal.SQLite.getVaultList());
        FolderTree.setModel(com.xahertz.internal.SQLite.allTablesList());
        Passwords_Table.setModel(com.xahertz.internal.Functions.vltTableModel("Root"));
        Container_Deck.show(Container, "vault");
        EnableVaultDataManipulationFunctions();
        Open_Vault_Button.setEnabled(false);
        New_Vault_MenuItem.setEnabled(false);
        Open_Vault_MenuItem.setEnabled(false);
        Close_Vault_Button.setEnabled(true);
        Copy_Username_Button.setEnabled(true);
        Copy_Password_Button.setEnabled(true);
        Copy_URL_Button.setEnabled(true);
        Close_Vault_MenuItem.setEnabled(true);
        Copy_Username_MenuItem.setEnabled(true);
        Copy_Password_MenuItem.setEnabled(true);
        Copy_URL_MenuItem.setEnabled(true);
        AutoType_Menu.setEnabled(true);
    }
    
    private void CloseVaultPage() {
        Container_Deck.show(Container, "start");
        DisableVaultDataManipulationFunctions();
        Open_Vault_Button.setEnabled(true);
        New_Vault_MenuItem.setEnabled(true);
        Open_Vault_MenuItem.setEnabled(true);
        Close_Vault_Button.setEnabled(false);
        Copy_Username_Button.setEnabled(false);
        Copy_Password_Button.setEnabled(false);
        Copy_URL_Button.setEnabled(false);
        Close_Vault_MenuItem.setEnabled(false);
        Copy_Username_MenuItem.setEnabled(false);
        Copy_Password_MenuItem.setEnabled(false);
        Copy_URL_MenuItem.setEnabled(false);
        AutoType_Menu.setEnabled(false);
    }
    
    private void EnableVaultDataManipulationFunctions() {
        New_Entry_Button.setEnabled(true);
        Edit_Entry_Button.setEnabled(true);
        Delete_Entry_Button.setEnabled(true);
        New_Entry_MenuItem.setEnabled(true);
        Edit_Entry_MenuItem.setEnabled(true);
        Delete_Entry_MenuItem.setEnabled(true);
        New_Group_MenuItem.setEnabled(true);
        Edit_Group_MenuItem.setEnabled(true);
        Delete_Group_MenuItem.setEnabled(true);
    }
    
    private void DisableVaultDataManipulationFunctions() {
        New_Entry_Button.setEnabled(false);
        Edit_Entry_Button.setEnabled(false);
        Delete_Entry_Button.setEnabled(false);
        New_Entry_MenuItem.setEnabled(false);
        Edit_Entry_MenuItem.setEnabled(false);
        Delete_Entry_MenuItem.setEnabled(false);
        New_Group_MenuItem.setEnabled(false);
        Edit_Group_MenuItem.setEnabled(false);
        Delete_Group_MenuItem.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLightLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatLightLaf is not available, stay with the default look and feel. */
        com.formdev.flatlaf.FlatLightLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLightLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
        
        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                com.xahertz.internal.SQLite.closeVault();
                com.xahertz.internal.SQLite.closeVaultList();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JMenuItem About_MenuItem;
    private javax.swing.JMenuItem AutoType_All_MenuItem;
    private javax.swing.JMenu AutoType_Menu;
    private javax.swing.JMenuItem AutoType_Password_MenuItem;
    private javax.swing.JMenuItem AutoType_Usename_MenuItem;
    private javax.swing.JButton Browse_Button;
    private javax.swing.JButton Close_Vault_Button;
    private javax.swing.JMenuItem Close_Vault_MenuItem;
    private javax.swing.JPasswordField Confirm_Password_Field;
    private javax.swing.JLabel Confirm_Password_Label;
    private javax.swing.JPanel Container;
    private javax.swing.JButton Copy_Password_Button;
    private javax.swing.JMenuItem Copy_Password_MenuItem;
    private javax.swing.JButton Copy_URL_Button;
    private javax.swing.JMenuItem Copy_URL_MenuItem;
    private javax.swing.JButton Copy_Username_Button;
    private javax.swing.JMenuItem Copy_Username_MenuItem;
    private javax.swing.JButton Delete_Entry_Button;
    private javax.swing.JMenuItem Delete_Entry_MenuItem;
    private javax.swing.JMenuItem Delete_Group_MenuItem;
    private javax.swing.JPanel Details_Panel;
    private javax.swing.JButton Edit_Entry_Button;
    private javax.swing.JMenuItem Edit_Entry_MenuItem;
    private javax.swing.JMenuItem Edit_Group_MenuItem;
    private javax.swing.JMenu Edit_Menu;
    private javax.swing.JPopupMenu.Separator Edit_Menu_Separator_One;
    private javax.swing.JPopupMenu.Separator Edit_Menu_Separator_Two;
    private javax.swing.JPanel EntryPage;
    private javax.swing.JButton EntryPage_Cancel_Button;
    private javax.swing.JPanel EntryPage_Container;
    private javax.swing.JButton EntryPage_Finish_Button;
    private javax.swing.JLabel EntryPage_Label;
    private javax.swing.JMenuItem Exit_MenuItem;
    private javax.swing.JTree FolderTree;
    private javax.swing.JPopupMenu FolderTree_PopupMenu;
    private javax.swing.JScrollPane FolderTree_ScrollPane;
    private javax.swing.JButton Generate_Password_Button;
    private javax.swing.JMenu Help_Menu;
    private javax.swing.JToolBar Main_ToolBar;
    private javax.swing.JMenuBar Menu_Bar;
    private javax.swing.JPanel NewVaultPage;
    private javax.swing.JButton NewVault_Cancel_Button;
    private javax.swing.JPanel NewVault_Container;
    private javax.swing.JButton NewVault_Finish_Button;
    private javax.swing.JLabel NewVault_Label;
    private javax.swing.JButton New_Entry_Button;
    private javax.swing.JMenuItem New_Entry_MenuItem;
    private javax.swing.JMenuItem New_Group_MenuItem;
    private javax.swing.JMenuItem New_Vault_MenuItem;
    private javax.swing.JLabel Notes_Label;
    private javax.swing.JScrollPane Notes_ScrollPane;
    private javax.swing.JTextArea Notes_TextArea;
    private javax.swing.JButton Open_Vault_Button;
    private javax.swing.JMenuItem Open_Vault_MenuItem;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JButton Password_Generator_Button;
    private javax.swing.JMenuItem Password_Generator_MenuItem;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JTable Passwords_Table;
    private javax.swing.JPopupMenu Passwords_Table_PopupMenu;
    private javax.swing.JScrollPane Passwords_Table_ScrollPane;
    private javax.swing.JLabel Recent_Vaults_Label;
    private javax.swing.JList<String> Recent_Vaults_List;
    private javax.swing.JScrollPane Recent_Vaults_ScrollPane;
    private javax.swing.JPanel StartPage;
    private javax.swing.JButton StartPage_Create_Vault_Button;
    private javax.swing.JButton StartPage_Open_Vault_Button;
    private javax.swing.JMenuItem Table_PopupMenu_Copy_Password;
    private javax.swing.JMenuItem Table_PopupMenu_Copy_URL;
    private javax.swing.JMenuItem Table_PopupMenu_Copy_Username;
    private javax.swing.JMenuItem Table_PopupMenu_Delete_Entry;
    private javax.swing.JMenuItem Table_PopupMenu_Edit_Entry;
    private javax.swing.JMenuItem Table_PopupMenu_New_Entry;
    private javax.swing.JPopupMenu.Separator Table_PopupMenu_Separator;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JTextField Title_TextField;
    private javax.swing.JToolBar.Separator ToolBar_Separator_One;
    private javax.swing.JToolBar.Separator ToolBar_Separator_Three;
    private javax.swing.JToolBar.Separator ToolBar_Separator_Two;
    private javax.swing.JMenu Tools_Menu;
    private javax.swing.JMenuItem Tree_PopupMenu_Delete_Group;
    private javax.swing.JMenuItem Tree_PopupMenu_Edit_Group;
    private javax.swing.JMenuItem Tree_PopupMenu_New_Group;
    private javax.swing.JLabel URL_Label;
    private javax.swing.JTextField URL_TextField;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JTextField Username_TextField;
    private javax.swing.JPanel VaultPage;
    private javax.swing.JPanel Vault_Actions_Panel;
    private javax.swing.JTextField Vault_Location_Field;
    private javax.swing.JLabel Vault_Location_Label;
    private javax.swing.JMenu Vault_Menu;
    private javax.swing.JPopupMenu.Separator Vault_Menu_Separator_One;
    private javax.swing.JTextField Vault_Name_Field;
    private javax.swing.JLabel Vault_Name_Label;
    private javax.swing.JPasswordField Vault_Password_Field;
    private javax.swing.JLabel Vault_Password_Label;
    private javax.swing.JLabel Welcome_Label;
    // End of variables declaration//GEN-END:variables
    private final java.awt.CardLayout Container_Deck;
    public static String Vault_Table_Name;
    public static String Version;
}
