package com.xahertz.sentinel;

/**
 *
 * @author XaHertz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        com.xahertz.internal.Function.initData();
        initComponents();
        Container_Deck = (java.awt.CardLayout)Container.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_ToolBar = new javax.swing.JToolBar();
        Open_Vault_Button = new javax.swing.JButton();
        Close_Vault_Button = new javax.swing.JButton();
        ToolBar_Separator_One = new javax.swing.JToolBar.Separator();
        New_Entry_Button = new javax.swing.JButton();
        Delete_Entry_Button = new javax.swing.JButton();
        ToolBar_Separator_Two = new javax.swing.JToolBar.Separator();
        Settings_Button = new javax.swing.JButton();
        About_Button = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        StartPage = new javax.swing.JPanel();
        Welcome_Label = new javax.swing.JLabel();
        Vault_Actions_Panel = new javax.swing.JPanel();
        StartPage_Create_Vault_Button = new javax.swing.JButton();
        StartPage_Open_Vault_Button = new javax.swing.JButton();
        StartPage_Import_File_Button = new javax.swing.JButton();
        Recent_Vaults_Label = new javax.swing.JLabel();
        Recent_Vaults_ScrollPane = new javax.swing.JScrollPane();
        Recent_Vaults_List = new javax.swing.JList<>();
        VaultPage = new javax.swing.JPanel();
        FolderTree_ScrollPane = new javax.swing.JScrollPane();
        FolderTree = new javax.swing.JTree();
        Passwords_Table_ScrollPane = new javax.swing.JScrollPane();
        Passwords_Table = new javax.swing.JTable();
        Details_Panel = new javax.swing.JPanel();
        Menu_Bar = new javax.swing.JMenuBar();
        Vault_Menu = new javax.swing.JMenu();
        New_Vault_MenuItem = new javax.swing.JMenuItem();
        Open_Vault_MenuItem = new javax.swing.JMenuItem();
        Close_Vault_MenuItem = new javax.swing.JMenuItem();
        Vault_Menu_Separator_One = new javax.swing.JPopupMenu.Separator();
        Exit_MenuItem = new javax.swing.JMenuItem();
        Edit_Menu = new javax.swing.JMenu();
        New_Entry_MenuItem = new javax.swing.JMenuItem();
        Edit_Entry_MenuItem = new javax.swing.JMenuItem();
        Delete_Entry_MenuItem = new javax.swing.JMenuItem();
        Edit_Menu_Separator_One = new javax.swing.JPopupMenu.Separator();
        New_Group_MenuItem = new javax.swing.JMenuItem();
        Edit_Group_MenuItem = new javax.swing.JMenuItem();
        Delete_Group_MenuItem = new javax.swing.JMenuItem();
        Edit_Menu_Separator_Two = new javax.swing.JPopupMenu.Separator();
        Copy_Username_MenuItem = new javax.swing.JMenuItem();
        Copy_Password_MenuItem = new javax.swing.JMenuItem();
        Tools_Menu = new javax.swing.JMenu();
        Password_Generator_MenuItem = new javax.swing.JMenuItem();
        AutoType_Menu = new javax.swing.JMenu();
        AutoType_All_MenuItem = new javax.swing.JMenuItem();
        AutoType_Usename_MenuItem = new javax.swing.JMenuItem();
        AutoType_Password_MenuItem = new javax.swing.JMenuItem();
        Help_Menu = new javax.swing.JMenu();
        About_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sentinel");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/app-icon.png")).getImage());
        setLocationByPlatform(true);

        Main_ToolBar.setRollover(true);

        Open_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        Open_Vault_Button.setToolTipText("Open Existing Vault");
        Open_Vault_Button.setFocusable(false);
        Open_Vault_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Open_Vault_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Open_Vault_Button);

        Close_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vault.png"))); // NOI18N
        Close_Vault_Button.setToolTipText("Close Vault");
        Close_Vault_Button.setFocusable(false);
        Close_Vault_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close_Vault_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Close_Vault_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_Vault_ButtonActionPerformed(evt);
            }
        });
        Main_ToolBar.add(Close_Vault_Button);
        Main_ToolBar.add(ToolBar_Separator_One);

        New_Entry_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        New_Entry_Button.setToolTipText("Add a New Entry");
        New_Entry_Button.setFocusable(false);
        New_Entry_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New_Entry_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(New_Entry_Button);

        Delete_Entry_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        Delete_Entry_Button.setToolTipText("Delete Entry");
        Delete_Entry_Button.setFocusable(false);
        Delete_Entry_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Delete_Entry_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Delete_Entry_Button);
        Main_ToolBar.add(ToolBar_Separator_Two);

        Settings_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        Settings_Button.setFocusable(false);
        Settings_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Settings_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(Settings_Button);

        About_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        About_Button.setFocusable(false);
        About_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        About_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Main_ToolBar.add(About_Button);

        Container.setLayout(new java.awt.CardLayout());

        Welcome_Label.setFont(Welcome_Label.getFont().deriveFont(Welcome_Label.getFont().getSize()+24f));
        Welcome_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome_Label.setText("Welcome to Sentinel");

        Vault_Actions_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StartPage_Create_Vault_Button.setFont(StartPage_Create_Vault_Button.getFont().deriveFont(StartPage_Create_Vault_Button.getFont().getStyle() | java.awt.Font.BOLD, StartPage_Create_Vault_Button.getFont().getSize()+2));
        StartPage_Create_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vault.png"))); // NOI18N
        StartPage_Create_Vault_Button.setText("Create Vault");
        StartPage_Create_Vault_Button.setToolTipText("Create New Vault");
        StartPage_Create_Vault_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPage_Create_Vault_ButtonActionPerformed(evt);
            }
        });

        StartPage_Open_Vault_Button.setFont(StartPage_Open_Vault_Button.getFont().deriveFont(StartPage_Open_Vault_Button.getFont().getStyle() | java.awt.Font.BOLD, StartPage_Open_Vault_Button.getFont().getSize()+2));
        StartPage_Open_Vault_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        StartPage_Open_Vault_Button.setText("Open Vault");
        StartPage_Open_Vault_Button.setToolTipText("Open Existing Vault");

        StartPage_Import_File_Button.setFont(StartPage_Import_File_Button.getFont().deriveFont(StartPage_Import_File_Button.getFont().getStyle() | java.awt.Font.BOLD, StartPage_Import_File_Button.getFont().getSize()+2));
        StartPage_Import_File_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        StartPage_Import_File_Button.setText("Import File");
        StartPage_Import_File_Button.setToolTipText("Import Passwords From CSV File");

        Recent_Vaults_Label.setFont(Recent_Vaults_Label.getFont().deriveFont(Recent_Vaults_Label.getFont().getStyle() | java.awt.Font.BOLD));
        Recent_Vaults_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Recent_Vaults_Label.setText("Recent Vaults");

        Recent_Vaults_List.setModel(com.xahertz.internal.Function.VaultList());
        Recent_Vaults_ScrollPane.setViewportView(Recent_Vaults_List);

        javax.swing.GroupLayout Vault_Actions_PanelLayout = new javax.swing.GroupLayout(Vault_Actions_Panel);
        Vault_Actions_Panel.setLayout(Vault_Actions_PanelLayout);
        Vault_Actions_PanelLayout.setHorizontalGroup(
            Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vault_Actions_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Recent_Vaults_ScrollPane)
                    .addGroup(Vault_Actions_PanelLayout.createSequentialGroup()
                        .addComponent(StartPage_Create_Vault_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StartPage_Open_Vault_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StartPage_Import_File_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Recent_Vaults_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Vault_Actions_PanelLayout.setVerticalGroup(
            Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vault_Actions_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Vault_Actions_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartPage_Create_Vault_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartPage_Open_Vault_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartPage_Import_File_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Recent_Vaults_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recent_Vaults_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout StartPageLayout = new javax.swing.GroupLayout(StartPage);
        StartPage.setLayout(StartPageLayout);
        StartPageLayout.setHorizontalGroup(
            StartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPageLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(StartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vault_Actions_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Welcome_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        StartPageLayout.setVerticalGroup(
            StartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPageLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(Welcome_Label)
                .addGap(18, 18, 18)
                .addComponent(Vault_Actions_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        Container.add(StartPage, "start");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Vault Home");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Internet");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Social");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Work");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Entertainment");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Offline");
        treeNode1.add(treeNode2);
        FolderTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        FolderTree_ScrollPane.setViewportView(FolderTree);

        Passwords_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Username", "URL", "Notes"
            }
        ));
        Passwords_Table_ScrollPane.setViewportView(Passwords_Table);

        Details_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout Details_PanelLayout = new javax.swing.GroupLayout(Details_Panel);
        Details_Panel.setLayout(Details_PanelLayout);
        Details_PanelLayout.setHorizontalGroup(
            Details_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Details_PanelLayout.setVerticalGroup(
            Details_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout VaultPageLayout = new javax.swing.GroupLayout(VaultPage);
        VaultPage.setLayout(VaultPageLayout);
        VaultPageLayout.setHorizontalGroup(
            VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VaultPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FolderTree_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwords_Table_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addComponent(Details_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        VaultPageLayout.setVerticalGroup(
            VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VaultPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VaultPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FolderTree_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(VaultPageLayout.createSequentialGroup()
                        .addComponent(Passwords_Table_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Details_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Container.add(VaultPage, "vault");

        Vault_Menu.setText("Vault");

        New_Vault_MenuItem.setText("New Vault");
        Vault_Menu.add(New_Vault_MenuItem);

        Open_Vault_MenuItem.setText("Open Vault");
        Open_Vault_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Vault_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(Open_Vault_MenuItem);

        Close_Vault_MenuItem.setText("Close Vault");
        Close_Vault_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_Vault_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(Close_Vault_MenuItem);
        Vault_Menu.add(Vault_Menu_Separator_One);

        Exit_MenuItem.setText("Exit");
        Exit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_MenuItemActionPerformed(evt);
            }
        });
        Vault_Menu.add(Exit_MenuItem);

        Menu_Bar.add(Vault_Menu);

        Edit_Menu.setText("Edit");

        New_Entry_MenuItem.setText("New Entry");
        Edit_Menu.add(New_Entry_MenuItem);

        Edit_Entry_MenuItem.setText("Edit Entry");
        Edit_Menu.add(Edit_Entry_MenuItem);

        Delete_Entry_MenuItem.setText("Delete Entry");
        Edit_Menu.add(Delete_Entry_MenuItem);
        Edit_Menu.add(Edit_Menu_Separator_One);

        New_Group_MenuItem.setText("New Group");
        Edit_Menu.add(New_Group_MenuItem);

        Edit_Group_MenuItem.setText("Edit Group");
        Edit_Menu.add(Edit_Group_MenuItem);

        Delete_Group_MenuItem.setText("Delete Group");
        Edit_Menu.add(Delete_Group_MenuItem);
        Edit_Menu.add(Edit_Menu_Separator_Two);

        Copy_Username_MenuItem.setText("Copy Username");
        Edit_Menu.add(Copy_Username_MenuItem);

        Copy_Password_MenuItem.setText("Copy Password");
        Edit_Menu.add(Copy_Password_MenuItem);

        Menu_Bar.add(Edit_Menu);

        Tools_Menu.setText("Tools");

        Password_Generator_MenuItem.setText("Password Generator");
        Tools_Menu.add(Password_Generator_MenuItem);

        AutoType_Menu.setText("Perform Auto-Type");

        AutoType_All_MenuItem.setText("Username and Password");
        AutoType_Menu.add(AutoType_All_MenuItem);

        AutoType_Usename_MenuItem.setText("Username");
        AutoType_Menu.add(AutoType_Usename_MenuItem);

        AutoType_Password_MenuItem.setText("Password");
        AutoType_Menu.add(AutoType_Password_MenuItem);

        Tools_Menu.add(AutoType_Menu);

        Menu_Bar.add(Tools_Menu);

        Help_Menu.setText("Help");

        About_MenuItem.setText("About");
        Help_Menu.add(About_MenuItem);

        Menu_Bar.add(Help_Menu);

        setJMenuBar(Menu_Bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Main_ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Main_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_MenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_MenuItemActionPerformed

    private void StartPage_Create_Vault_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPage_Create_Vault_ButtonActionPerformed
        Container_Deck.show(Container, "vault");
    }//GEN-LAST:event_StartPage_Create_Vault_ButtonActionPerformed

    private void Close_Vault_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_Vault_ButtonActionPerformed
        Container_Deck.show(Container, "start");
    }//GEN-LAST:event_Close_Vault_ButtonActionPerformed

    private void Close_Vault_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_Vault_MenuItemActionPerformed
        Container_Deck.show(Container, "start");
    }//GEN-LAST:event_Close_Vault_MenuItemActionPerformed

    private void Open_Vault_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Vault_MenuItemActionPerformed
        Container_Deck.show(Container, "vault");
    }//GEN-LAST:event_Open_Vault_MenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLightLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatLightLaf is not available, stay with the default look and feel. */
        com.formdev.flatlaf.FlatLightLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLightLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JMenuItem About_MenuItem;
    private javax.swing.JMenuItem AutoType_All_MenuItem;
    private javax.swing.JMenu AutoType_Menu;
    private javax.swing.JMenuItem AutoType_Password_MenuItem;
    private javax.swing.JMenuItem AutoType_Usename_MenuItem;
    private javax.swing.JButton Close_Vault_Button;
    private javax.swing.JMenuItem Close_Vault_MenuItem;
    private javax.swing.JPanel Container;
    private javax.swing.JMenuItem Copy_Password_MenuItem;
    private javax.swing.JMenuItem Copy_Username_MenuItem;
    private javax.swing.JButton Delete_Entry_Button;
    private javax.swing.JMenuItem Delete_Entry_MenuItem;
    private javax.swing.JMenuItem Delete_Group_MenuItem;
    private javax.swing.JPanel Details_Panel;
    private javax.swing.JMenuItem Edit_Entry_MenuItem;
    private javax.swing.JMenuItem Edit_Group_MenuItem;
    private javax.swing.JMenu Edit_Menu;
    private javax.swing.JPopupMenu.Separator Edit_Menu_Separator_One;
    private javax.swing.JPopupMenu.Separator Edit_Menu_Separator_Two;
    private javax.swing.JMenuItem Exit_MenuItem;
    private javax.swing.JTree FolderTree;
    private javax.swing.JScrollPane FolderTree_ScrollPane;
    private javax.swing.JMenu Help_Menu;
    private javax.swing.JToolBar Main_ToolBar;
    private javax.swing.JMenuBar Menu_Bar;
    private javax.swing.JButton New_Entry_Button;
    private javax.swing.JMenuItem New_Entry_MenuItem;
    private javax.swing.JMenuItem New_Group_MenuItem;
    private javax.swing.JMenuItem New_Vault_MenuItem;
    private javax.swing.JButton Open_Vault_Button;
    private javax.swing.JMenuItem Open_Vault_MenuItem;
    private javax.swing.JMenuItem Password_Generator_MenuItem;
    private javax.swing.JTable Passwords_Table;
    private javax.swing.JScrollPane Passwords_Table_ScrollPane;
    private javax.swing.JLabel Recent_Vaults_Label;
    private javax.swing.JList<String> Recent_Vaults_List;
    private javax.swing.JScrollPane Recent_Vaults_ScrollPane;
    private javax.swing.JButton Settings_Button;
    private javax.swing.JPanel StartPage;
    private javax.swing.JButton StartPage_Create_Vault_Button;
    private javax.swing.JButton StartPage_Import_File_Button;
    private javax.swing.JButton StartPage_Open_Vault_Button;
    private javax.swing.JToolBar.Separator ToolBar_Separator_One;
    private javax.swing.JToolBar.Separator ToolBar_Separator_Two;
    private javax.swing.JMenu Tools_Menu;
    private javax.swing.JPanel VaultPage;
    private javax.swing.JPanel Vault_Actions_Panel;
    private javax.swing.JMenu Vault_Menu;
    private javax.swing.JPopupMenu.Separator Vault_Menu_Separator_One;
    private javax.swing.JLabel Welcome_Label;
    // End of variables declaration//GEN-END:variables
    private final java.awt.CardLayout Container_Deck;
}
